### ISSUE TITLE
About button doesn't work

### ISSUE THREAD

**Issue by jerryhuang2k** [NullKZ/dolldb#1]

**Comment by nkzou** [comment]
not compatible with netscape, sorry. please update your browser

**Comment by jerryhuang2k** [comment]
I believe this line of code is wrong, should link to about page.
`<a href="#" class="btn btn-link">About</a>`

**Comment by nkzou** [comment]
fixed in https://github.com/NullKZ/dolldb/commit/4d716f724f7e7a2f1eeabcab98045ed1782df7d1
